---
- fail:
    msg: "Set the Github API key in vars/main.yml"
  when: GITHUB_API_KEY == "fill_me_in"

- name: Test cases
  block:

    - name: Failure case 1 - Invalid credentials
      block:
        - github_raw:
            api_key: "{{GITHUB_API_KEY}}a"
            endpoint: user
      rescue:
        - name: Failure case 1 - Invalid credentials
          assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == "Failed to authorise due to invalid credentials."

    - name: Failure case 2 - Failed request
      block:
        - github_raw:
            api_key: "{{GITHUB_API_KEY}}"
            endpoint: user/repos
            method: POST
            data:
              namme: test-repo
      rescue:
        - name: Failure case 2 - Failed request
          assert:
            that:
              - ansible_failed_result is defined
              - '"Request failed with reason" in ansible_failed_result.msg'

    - name: Success case
      block:
        - github_raw:
            api_key: "{{GITHUB_API_KEY}}"
            endpoint: user
          register: response

        - name: Success case
          assert:
            that:
              - response.payload is defined
              - response.payload.node_id is defined